services:
    # Backend API
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - DEBUG=true
            - REDIS_URL=redis://redis:6379
            - DEFAULT_LANGUAGE=vi-VN
        volumes:
            - ./backend:/app
        depends_on:
            - redis
        restart: unless-stopped

    # Redis for caching and session management
    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        restart: unless-stopped
